//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PV.DL.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleVentas
    {
        public int DetalleVentaId { get; set; }
        public int ProductoId { get; set; }
        public double Cantidad { get; set; }
        public System.DateTime FechaVenta { get; set; }
        public int UsuarioId { get; set; }
        public int VentaId { get; set; }
        public int Total { get; set; }
        public int TipoPagoId { get; set; }
    
        public virtual Productos Productos { get; set; }
        public virtual TipoPagos TipoPagos { get; set; }
        public virtual TipoProductos TipoProductos { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        public virtual Ventas Ventas { get; set; }
    }
}
