//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PV.DL.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sesiones
    {
        public int SesionId { get; set; }
        public int UsuarioId { get; set; }
        public int RolId { get; set; }
        public string Activo { get; set; }
        public System.DateTime FechaInicioSesion { get; set; }
        public System.DateTime FechaCierreSesion { get; set; }
    
        public virtual Roles Roles { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
