//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PV.DL.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ventas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ventas()
        {
            this.DetalleVentas = new HashSet<DetalleVentas>();
        }
    
        public int VentaId { get; set; }
        public int ProductoId { get; set; }
        public double Precio { get; set; }
        public double Efectivo { get; set; }
        public double Cambio { get; set; }
        public System.DateTime Fecha { get; set; }
        public int UsuarioId { get; set; }
        public int TipoPagoId { get; set; }
        public double Total { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleVentas> DetalleVentas { get; set; }
        public virtual TipoPagos TipoPagos { get; set; }
        public virtual TipoProductos TipoProductos { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
